# Assignment on Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Generate a 5x4 array of random numbers between 0 and 100
np.random.seed(42)  # For reproducibility
random_array = np.random.randint(0, 100, size=(5, 4))

In [3]:
# Convert to DataFrame with custom row and column names
df = pd.DataFrame(random_array, columns=['A', 'B', 'C', 'D'], index=['V', 'W', 'X', 'Y', 'Z'])

In [7]:
print(random_array,"\n",df)

[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]
 [ 1 87 29 37]] 
     A   B   C   D
V  51  92  14  71
W  60  20  82  86
X  74  74  87  99
Y  23   2  21  52
Z   1  87  29  37


In [8]:
# Select rows 'W' to 'Y'
print(df.loc['W':'Y'])


    A   B   C   D
W  60  20  82  86
X  74  74  87  99
Y  23   2  21  52


In [9]:
# Select first 3 rows
print(df.iloc[:3])


    A   B   C   D
V  51  92  14  71
W  60  20  82  86
X  74  74  87  99


In [10]:
# Select columns 'A' and 'C'
print(df[['A', 'C']])


    A   C
V  51  14
W  60  82
X  74  87
Y  23  21
Z   1  29


# Selecting Specific Rows and Columns

In [11]:
# Select rows 'W' to 'Y' and columns 'B' and 'D'
print(df.loc['W':'Y', ['B', 'D']])

    B   D
W  20  86
X  74  99
Y   2  52


In [12]:
# Select first 3 rows and first 2 columns
print(df.iloc[:3, :2])

    A   B
V  51  92
W  60  20
X  74  74


# Conditional Slicing

In [13]:
# Select rows where column 'A' values are greater than 50
print(df[df['A'] > 50])

    A   B   C   D
V  51  92  14  71
W  60  20  82  86
X  74  74  87  99


In [14]:
# Select rows where column 'C' values are less than 30
print(df[df['C'] < 30])


    A   B   C   D
V  51  92  14  71
Y  23   2  21  52
Z   1  87  29  37


# Dropping a Row

In [15]:
# Drop row 'X'
df_dropped_row = df.drop(index='X')


In [16]:
# Display DataFrame after dropping row
print(df_dropped_row)


    A   B   C   D
V  51  92  14  71
W  60  20  82  86
Y  23   2  21  52
Z   1  87  29  37


# Note: This does not modify the original DataFrame unless inplace=True.

# Dropping Multiple Rows

In [17]:
# Drop rows 'W' and 'Y'
df_dropped_rows = df.drop(index=['W', 'Y'])
print(df_dropped_rows)


    A   B   C   D
V  51  92  14  71
X  74  74  87  99
Z   1  87  29  37


# Dropping a Column

In [18]:
# Drop column 'C'
df_dropped_col = df.drop(columns='C')
print(df_dropped_col)


    A   B   D
V  51  92  71
W  60  20  86
X  74  74  99
Y  23   2  52
Z   1  87  37


# Dropping Multiple Columns

In [19]:
# Drop columns 'A' and 'D'
df_dropped_cols = df.drop(columns=['A', 'D'])
print(df_dropped_cols)


    B   C
V  92  14
W  20  82
X  74  87
Y   2  21
Z  87  29


# Dropping Rows/Columns In-Place

## If you want to modify the original DataFrame directly, use inplace=True:


In [20]:
# Drop row 'X' permanently
df.drop(index='X', inplace=True)


In [21]:
# Drop column 'C' permanently
df.drop(columns='C', inplace=True)


In [22]:
print(df)

    A   B   D
V  51  92  71
W  60  20  86
Y  23   2  52
Z   1  87  37


In [27]:
# Adding a new column first
df['F'] = [5, 10, 15, 20]

In [31]:
# Adding a new row that includes the new column
df.loc['Extra'] = [55, 65, 75, 85] 


In [32]:
print(df)

        A   B   D   F
V      51  92  71   5
W      60  20  86  10
Y      23   2  52  15
Z       1  87  37  20
Extra  55  65  75  85
